# Vaja: Phone prices

In [1]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

## Treniranje modela

Podatki za trening so na voljo v datoteki: `data/vaja/mobile_clean.csv`

In [2]:
data = mobile_data = pd.read_csv("data/vaja/mobile_clean.csv", index_col="product_id")

In [3]:
data.shape

(151, 13)

In [4]:
data.describe()

,price,sale,weight,resoloution,ppi,cpu_core,cpu_freq,internal_mem,ram,rearcam,front_cam,battery,thickness
count,151.000000,151.000000,151.000000,151.000000,151.000000,151.000000,151.000000,151.000000,151.000000,151.000000,151.000000,151.000000,151.000000
mean,550.889073,591.980132,167.556954,5.160927,334.516556,4.794702,1.501331,24.058119,2.175523,10.231126,4.415894,2809.668874,8.964901
std,195.212038,1469.778874,83.062901,1.447040,135.430172,2.463921,0.613407,28.381497,1.615576,6.236927,4.326925,1293.732671,2.230492
min,153.500000,10.000000,66.000000,1.400000,121.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,800.000000,5.100000
25%,433.500000,37.000000,134.050000,4.800000,233.000000,4.000000,1.200000,8.000000,1.000000,5.000000,0.000000,2020.000000,7.600000
50%,564.500000,109.000000,153.000000,5.150000,294.000000,4.000000,1.400000,16.000000,2.000000,12.000000,5.000000,2800.000000,8.500000
75%,686.000000,380.000000,170.000000,5.500000,430.000000,8.000000,1.875000,32.000000,3.000000,16.000000,6.550000,3240.000000,9.850000
max,1090.250000,9807.000000,753.000000,12.200000,806.000000,8.000000,2.700000,128.000000,6.000000,23.000000,20.000000,9500.000000,18.500000

In [5]:
data.head()

,price,sale,weight,resoloution,ppi,cpu_core,cpu_freq,internal_mem,ram,rearcam,front_cam,battery,thickness
product_id,,,,,,,,,,,,,
203,589.25,10,135.0,5.2,424,8,1.35,16.0,3.000,13.00,8.0,2610,7.4
880,437.25,10,125.0,4.0,233,2,1.30,4.0,1.000,3.15,0.0,1700,9.9
40,479.00,10,110.0,4.7,312,4,1.20,8.0,1.500,13.00,5.0,2000,7.6
99,328.75,11,118.5,4.0,233,2,1.30,4.0,0.512,3.15,0.0,1400,11.0
880,437.25,11,125.0,4.0,233,2,1.30,4.0,1.000,3.15,0.0,1700,9.9

Pri oceni testnega modela vam je lahko v pomoč spodnja funkcija:

In [7]:
from sklearn.metrics import mean_squared_error

def get_scores(trained_model, X_train, X_test, y_train, y_test):
    pred = trained_model.predict(X_test)
    mse = np.sqrt(mean_squared_error(y_test, pred))
    print(f'Mean error: {mse:3.3}€ ({mse/np.mean(pred)*100:3.3}%)')
    print(f"Training set score: {trained_model.score(X_train, y_train):.2f}")
    print(f"Test set score: {trained_model.score(X_test, y_test):.2f}")

Cilj je ustvariti model, ki glede na značilke napove napove ceno telefona (cena je v €). Podatke skalirajte s `StandardScaler`.

In [6]:
X = data.drop(columns="price")
y = data["price"]